### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by jamieRowen** [ropenscilabs/opencv#2]
Hi, 

Really like the look of this package but am having some issues installing on ubuntu 16.04

I have installed libopencv-*  via apt and tried to install the R package from github via devtools and reach the following compilation error. 

`g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG -I/usr/include/opencv -I"/home/jamie/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c base.cpp -o base.o
base.cpp: In function ‘XPtrMat cvmat_resize(XPtrMat, int, int)’:
base.cpp:93:60: error: ‘INTER_LINEAR_EXACT’ was not declared in this scope
   cv::resize(input, output, cv::Size(width, height), 0, 0, INTER_LINEAR_EXACT);
                                                            ^
/usr/lib/R/etc/Makeconf:168: recipe for target 'base.o' failed
make: *** [base.o] Error 1
ERROR: compilation failed for package ‘opencv’
`

Do you have any ideas?

Thanks

**Comment by jamieRowen** [comment]
OK, my apologies, 

it did not compile with opencv 3.3.0 but does with 3.4.0 so closing
